apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactionmanagement
  labels:
    app: satisfactionmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satisfactionmanagement
  template:
    metadata:
      labels:
        app: satisfactionmanagement
    spec:
      containers:
        - name: satisfactionmanagement
          image: skcc13acr.azurecr.io/satisfactionmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5