apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactionmanagement
  labels:
    app: satisfactionmanagement
spec:
  replicas: 5
  selector:
    matchLabels:
      app: satisfactionmanagement
  template:
    metadata:
      labels:
        app: satisfactionmanagement
    spec:
      containers:
        - name: satisfactionmanagement
          image: skcc13acr.azurecr.io/satisfactionmanagement:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"